apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: my-custom-service-account
      automountServiceAccountToken: false
      containers:
      - name: my-app
        image: mikarotem/my-web-image:v1.0
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
          requests:
            memory: "64Mi"
            cpu: "250m"
            ephemeral-storage: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app

spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: my-app
