apiVersion: v1
kind: Pod
spec:
  imagePullSecrets:
    - name: mysec
  serviceAccountName: jenkins-agent
  containers:
  - name: agent
    image: 471112876520.dkr.ecr.eu-central-1.amazonaws.com/my-agent-image2:latest
    command: ["/bin/sh"]
    args: ["-c", "/usr/local/bin/docker-entrypoint.sh && tail -f /dev/null"]
    tty: true
    securityContext:
      privileged: true
      runAsUser: 0
    volumeMounts:
      - name: docker-graph-storage
        mountPath: /var/lib/docker
    env:
    - name: VAULT_TOKEN
      value: ""
  volumes:
  - name: docker-graph-storage
    emptyDir: {}
  - name: dind-socket
    emptyDir: {}