
apiVersion: v1
kind: Secret
metadata:
  name: weather-api-secret
type: Opaque
data:
  API_KEY: VjVYSlRGVURVUzc2UENCUEM0OVk4SktRMw==


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-image
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-web-image
  template:
    metadata:
      labels:
        app: my-web-image
    spec:
      serviceAccountName: ecr-access-sa  
      containers:
        - name: my-web-image
          image: 897729114707.dkr.ecr.eu-central-1.amazonaws.com/my-web-image:1.0.16
          ports:
            - containerPort: 5000
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: weather-api-secret
                  key: API_KEY
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10