apiVersion: v1
kind: Service
metadata:
  name: my-web-image-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"  
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing" 
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/" 
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval-seconds: "10"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout-seconds: "5"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "3"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
  labels:
    app: my-web-image
spec:
  type: LoadBalancer
  selector:
    app: my-web-image
  ports:
    - name: http
      protocol: TCP
      port: 80          
      targetPort: 5000  
